style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/tu-usuario/tu-repositorio
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
  commit_groups:
    title_maps:
      feat: "Nuevas Funcionalidades"
      fix: "Correcciones de Errores"
      perf: "Mejoras de Rendimiento"
      refactor: "Refactorizaciones"
  header:
    pattern: "^([\\w\\d]+)(?:\\(([\\w\\d\\-\\.]+)\\))?\\:\\s(.+)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE