name: Automated Changelog

on:
  push:
    branches:
      - master
      
jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up git-chglog
        run: |
          curl -L https://github.com/git-chglog/git-chglog/releases/download/v0.15.0/git-chglog_0.15.0_linux_amd64.tar.gz -o git-chglog.tar.gz
          tar -xzf git-chglog.tar.gz
          sudo mv git-chglog /usr/local/bin/

      - name: Generate CHANGELOG
        run: |
          # Verifica si hay tags en el repositorio
          if [ -z "$(git tag)" ]; then
            echo "No tags found. Generating CHANGELOG with a simulated tag."
            git-chglog --next-tag v0.0.0 -o CHANGELOG.md
          else
            echo "Tags found. Generating CHANGELOG normally."
            git-chglog -o CHANGELOG.md
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md [skip ci]"
          git push